pipeline {
  agent any

  stages {
    stage ('Build') {
       steps {
         script {
          docker.build("my-nginx:${env.BUILD_ID}")
         }
       }
    }
    stage ('Teste kubernetes') {
      stage('Apply Kubernetes files') {
        withKubeConfig([credentialsId: 'kubeconfig', serverUrl: 'https://192.168.0.150:6443']) {
          sh 'kubectl get namespaces'
        }
      }
    }
  }
}
